import type { Media, User } from '@/payload-types'
import { RequiredDataFromCollectionSlug } from 'payload'

export type PostArgs = {
  heroImage: Media
  blockImage: Media
  author: User
}

export const post3: (args: PostArgs) => RequiredDataFromCollectionSlug<'posts'> = ({
  heroImage,
  blockImage,
  author,
}) => {
  return {
    slug: 'spaces-commerce-integration',
    _status: 'published',
    authors: [author],
    content: {
      root: {
        type: 'root',
        children: [
          {
            type: 'heading',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Seamlessly integrate e-commerce capabilities into your collaborative spaces with multi-tenant marketplace features and AI-powered business insights.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            tag: 'h2',
            version: 1,
          },
          {
            type: 'block',
            fields: {
              blockName: 'Commerce Integration',
              blockType: 'banner',
              content: {
                root: {
                  type: 'root',
                  children: [
                    {
                      type: 'paragraph',
                      children: [
                        {
                          type: 'text',
                          detail: 0,
                          format: 1,
                          mode: 'normal',
                          style: '',
                          text: 'Commerce + Collaboration:',
                          version: 1,
                        },
                        {
                          type: 'text',
                          detail: 0,
                          format: 0,
                          mode: 'normal',
                          style: '',
                          text: ' Spaces now includes integrated e-commerce capabilities, allowing teams to collaborate on products, manage inventory, and process orders within the same platform.',
                          version: 1,
                        },
                      ],
                      direction: 'ltr',
                      format: '',
                      indent: 0,
                      textFormat: 0,
                      version: 1,
                    },
                  ],
                  direction: 'ltr',
                  format: '',
                  indent: 0,
                  version: 1,
                },
              },
              style: 'success',
            },
            format: '',
            version: 2,
          },
          {
            type: 'heading',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Multi-Tenant E-Commerce Architecture',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            tag: 'h2',
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Our commerce integration leverages the same multi-tenant architecture that powers Spaces collaboration. Each tenant gets isolated product catalogs, order management, and payment processing while maintaining seamless team collaboration around commerce activities.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'list',
            children: [
              {
                type: 'listitem',
                children: [
                  {
                    type: 'text',
                    detail: 0,
                    format: 1,
                    mode: 'normal',
                    style: '',
                    text: 'Tenant-Isolated Commerce:',
                    version: 1,
                  },
                  {
                    type: 'text',
                    detail: 0,
                    format: 0,
                    mode: 'normal',
                    style: '',
                    text: ' Complete separation of products, orders, and customer data',
                    version: 1,
                  },
                ],
                direction: 'ltr',
                format: '',
                indent: 0,
                version: 1,
                value: 1,
              },
              {
                type: 'listitem',
                children: [
                  {
                    type: 'text',
                    detail: 0,
                    format: 1,
                    mode: 'normal',
                    style: '',
                    text: 'Collaborative Product Management:',
                    version: 1,
                  },
                  {
                    type: 'text',
                    detail: 0,
                    format: 0,
                    mode: 'normal',
                    style: '',
                    text: ' Teams can discuss and refine products in dedicated channels',
                    version: 1,
                  },
                ],
                direction: 'ltr',
                format: '',
                indent: 0,
                version: 1,
                value: 2,
              },
              {
                type: 'listitem',
                children: [
                  {
                    type: 'text',
                    detail: 0,
                    format: 1,
                    mode: 'normal',
                    style: '',
                    text: 'Stripe Connect Integration:',
                    version: 1,
                  },
                  {
                    type: 'text',
                    detail: 0,
                    format: 0,
                    mode: 'normal',
                    style: '',
                    text: ' Multi-vendor marketplace with automated payouts',
                    version: 1,
                  },
                ],
                direction: 'ltr',
                format: '',
                indent: 0,
                version: 1,
                value: 3,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            listType: 'bullet',
            start: 1,
            tag: 'ul',
            version: 1,
          },
          {
            type: 'heading',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Commerce Collections Integration',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            tag: 'h3',
            version: 1,
          },
          {
            type: 'block',
            fields: {
              blockName: 'Commerce Schema',
              blockType: 'code',
              code: "// Integrated Commerce Collections\nconst Products = {\n  slug: 'products',\n  fields: [\n    { name: 'title', type: 'text', required: true },\n    { name: 'description', type: 'richText' },\n    { name: 'price', type: 'number', required: true },\n    { name: 'tenant', type: 'relationship', relationTo: 'tenants' },\n    { name: 'categories', type: 'relationship', relationTo: 'categories' },\n    { name: 'collaborationChannel', type: 'relationship', relationTo: 'channels' },\n    { name: 'aiInsights', type: 'group', fields: [\n      { name: 'marketAnalysis', type: 'textarea' },\n      { name: 'pricingRecommendations', type: 'textarea' },\n      { name: 'competitorData', type: 'json' }\n    ]}\n  ]\n}\n\nconst Orders = {\n  slug: 'orders',\n  fields: [\n    { name: 'customer', type: 'relationship', relationTo: 'users' },\n    { name: 'items', type: 'array', fields: [...] },\n    { name: 'tenant', type: 'relationship', relationTo: 'tenants' },\n    { name: 'orderChannel', type: 'relationship', relationTo: 'channels' },\n    { name: 'fulfillmentTeam', type: 'relationship', relationTo: 'space-members' }\n  ]\n}",
              language: 'javascript',
            },
            format: '',
            version: 2,
          },
          {
            type: 'heading',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'AI-Powered Commerce Intelligence',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            tag: 'h2',
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'The Business AI Agent extends its intelligence to commerce operations, providing real-time insights on product performance, customer behavior, and market opportunities directly within your collaboration channels.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'list',
            children: [
              {
                type: 'listitem',
                children: [
                  {
                    type: 'text',
                    detail: 0,
                    format: 0,
                    mode: 'normal',
                    style: '',
                    text: '📊 Real-time sales analytics and trend identification',
                    version: 1,
                  },
                ],
                direction: 'ltr',
                format: '',
                indent: 0,
                version: 1,
                value: 1,
              },
              {
                type: 'listitem',
                children: [
                  {
                    type: 'text',
                    detail: 0,
                    format: 0,
                    mode: 'normal',
                    style: '',
                    text: '🎯 Customer behavior analysis and segmentation',
                    version: 1,
                  },
                ],
                direction: 'ltr',
                format: '',
                indent: 0,
                version: 1,
                value: 2,
              },
              {
                type: 'listitem',
                children: [
                  {
                    type: 'text',
                    detail: 0,
                    format: 0,
                    mode: 'normal',
                    style: '',
                    text: '💡 Automated pricing recommendations based on market data',
                    version: 1,
                  },
                ],
                direction: 'ltr',
                format: '',
                indent: 0,
                version: 1,
                value: 3,
              },
              {
                type: 'listitem',
                children: [
                  {
                    type: 'text',
                    detail: 0,
                    format: 0,
                    mode: 'normal',
                    style: '',
                    text: '🚀 Product opportunity identification and launch strategies',
                    version: 1,
                  },
                ],
                direction: 'ltr',
                format: '',
                indent: 0,
                version: 1,
                value: 4,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            listType: 'bullet',
            start: 1,
            tag: 'ul',
            version: 1,
          },
          {
            type: 'block',
            fields: {
              blockName: '',
              blockType: 'mediaBlock',
              media: blockImage.id,
            },
            format: '',
            version: 2,
          },
          {
            type: 'heading',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Collaborative Commerce Workflows',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            tag: 'h2',
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Commerce operations become truly collaborative with dedicated channels for product development, order fulfillment, customer support, and inventory management. Teams can communicate in real-time while maintaining context with relevant commerce data.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'heading',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Multi-Vendor Marketplace Features',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            tag: 'h3',
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Built-in support for multi-vendor marketplaces with Stripe Connect enables complex commerce scenarios where multiple vendors can operate within the same space while maintaining separate financial accounts and collaboration channels.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'block',
            fields: {
              blockName: 'Stripe Integration',
              blockType: 'code',
              code: "// Multi-Vendor Payment Processing\nconst processMultiVendorPayment = async (order) => {\n  const vendors = order.items.map(item => item.vendor)\n  \n  // Create connected accounts for each vendor\n  const connectedAccounts = await Promise.all(\n    vendors.map(vendor => stripe.accounts.create({\n      type: 'express',\n      country: vendor.country,\n      email: vendor.email,\n      metadata: { \n        tenantId: vendor.tenant.id,\n        spaceId: vendor.space.id \n      }\n    }))\n  )\n  \n  // Process payment with automatic splits\n  return await stripe.paymentIntents.create({\n    amount: order.total,\n    currency: 'usd',\n    transfer_group: order.id,\n    on_behalf_of: connectedAccounts[0].id,\n    transfer_data: {\n      destination: connectedAccounts[0].id,\n    },\n  })\n}",
              language: 'javascript',
            },
            format: '',
            version: 2,
          },
          {
            type: 'block',
            fields: {
              blockName: 'Unified Commerce Experience',
              blockType: 'banner',
              content: {
                root: {
                  type: 'root',
                  children: [
                    {
                      type: 'paragraph',
                      children: [
                        {
                          type: 'text',
                          detail: 0,
                          format: 0,
                          mode: 'normal',
                          style: '',
                          text: 'Spaces Commerce Integration represents the future of collaborative e-commerce - where teams, AI, and customers converge in a unified platform that drives both innovation and sales.',
                          version: 1,
                        },
                      ],
                      direction: 'ltr',
                      format: '',
                      indent: 0,
                      textFormat: 0,
                      version: 1,
                    },
                  ],
                  direction: 'ltr',
                  format: '',
                  indent: 0,
                  version: 1,
                },
              },
              style: 'info',
            },
            format: '',
            version: 2,
          },
        ],
        direction: 'ltr',
        format: '',
        indent: 0,
        version: 1,
      },
    },
    heroImage: heroImage.id,
    meta: {
      description:
        'Discover how Spaces integrates powerful e-commerce capabilities with collaborative team features, multi-tenant architecture, and AI-powered business intelligence.',
      image: heroImage.id,
      title: 'Spaces Commerce: Collaborative E-Commerce Revolution',
    },
    relatedPosts: [], // this is populated by the seed script
    title: 'Spaces Commerce: Collaborative E-Commerce Revolution',
  }
}
