import type { Media, User } from '@/payload-types'
import { RequiredDataFromCollectionSlug } from 'payload'

export type PostArgs = {
  heroImage: Media
  blockImage: Media
  author: User
}

export const post4: (args: PostArgs) => RequiredDataFromCollectionSlug<'posts'> = ({
  heroImage,
  blockImage,
  author,
}) => {
  return {
    slug: 'vapi-scheduling-automation',
    _status: 'published',
    authors: [author],
    content: {
      root: {
        type: 'root',
        children: [
          {
            type: 'heading',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Intelligent voice AI that schedules meetings, follows up with prospects, and manages your entire sales pipeline through natural conversation.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            tag: 'h2',
            version: 1,
          },
          {
            type: 'block',
            fields: {
              blockName: 'VAPI Integration',
              blockType: 'banner',
              content: {
                root: {
                  type: 'root',
                  children: [
                    {
                      type: 'paragraph',
                      children: [
                        {
                          type: 'text',
                          detail: 0,
                          format: 1,
                          mode: 'normal',
                          style: '',
                          text: 'Voice AI Revolution:',
                          version: 1,
                        },
                        {
                          type: 'text',
                          detail: 0,
                          format: 0,
                          mode: 'normal',
                          style: '',
                          text: ' Spaces now includes VAPI.AI integration for intelligent voice assistants that can schedule appointments, follow up with leads, and maintain conversations within your collaboration channels.',
                          version: 1,
                        },
                      ],
                      direction: 'ltr',
                      format: '',
                      indent: 0,
                      textFormat: 0,
                      version: 1,
                    },
                  ],
                  direction: 'ltr',
                  format: '',
                  indent: 0,
                  version: 1,
                },
              },
              style: 'warning',
            },
            format: '',
            version: 2,
          },
          {
            type: 'heading',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Automated Scheduling Intelligence',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            tag: 'h2',
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Our VAPI-powered scheduling bot doesn\'t just book appointments - it understands context, reads calendar availability across team members, and can intelligently handle complex scheduling scenarios while maintaining a natural conversation flow.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'list',
            children: [
              {
                type: 'listitem',
                children: [
                  {
                    type: 'text',
                    detail: 0,
                    format: 1,
                    mode: 'normal',
                    style: '',
                    text: 'Intelligent Calendar Integration:',
                    version: 1,
                  },
                  {
                    type: 'text',
                    detail: 0,
                    format: 0,
                    mode: 'normal',
                    style: '',
                    text: ' Real-time availability checking across multiple team members',
                    version: 1,
                  },
                ],
                direction: 'ltr',
                format: '',
                indent: 0,
                version: 1,
                value: 1,
              },
              {
                type: 'listitem',
                children: [
                  {
                    type: 'text',
                    detail: 0,
                    format: 1,
                    mode: 'normal',
                    style: '',
                    text: 'Context-Aware Booking:',
                    version: 1,
                  },
                  {
                    type: 'text',
                    detail: 0,
                    format: 0,
                    mode: 'normal',
                    style: '',
                    text: ' Understands meeting types and automatically assigns appropriate team members',
                    version: 1,
                  },
                ],
                direction: 'ltr',
                format: '',
                indent: 0,
                version: 1,
                value: 2,
              },
              {
                type: 'listitem',
                children: [
                  {
                    type: 'text',
                    detail: 0,
                    format: 1,
                    mode: 'normal',
                    style: '',
                    text: 'Multi-Language Support:',
                    version: 1,
                  },
                  {
                    type: 'text',
                    detail: 0,
                    format: 0,
                    mode: 'normal',
                    style: '',
                    text: ' Natural conversation in 50+ languages with cultural awareness',
                    version: 1,
                  },
                ],
                direction: 'ltr',
                format: '',
                indent: 0,
                version: 1,
                value: 3,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            listType: 'bullet',
            start: 1,
            tag: 'ul',
            version: 1,
          },
          {
            type: 'heading',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'VAPI Integration Architecture',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            tag: 'h3',
            version: 1,
          },
          {
            type: 'block',
            fields: {
              blockName: 'VAPI Implementation',
              blockType: 'code',
              code: "// VAPI Scheduling Bot Integration\nclass VAPISchedulingBot {\n  constructor(config) {\n    this.vapi = new VAPI({\n      apiKey: config.vapiKey,\n      model: 'gpt-4-turbo-voice',\n      voice: 'nova-professional'\n    })\n    this.calendar = new CalendarService(config.calendarAuth)\n    this.spaces = new SpacesAPI(config.spacesAuth)\n  }\n\n  async handleIncomingCall(phoneNumber, spaceId) {\n    const caller = await this.identifyCaller(phoneNumber)\n    const context = await this.buildConversationContext(caller, spaceId)\n    \n    return await this.vapi.createCall({\n      phoneNumberId: phoneNumber,\n      assistant: {\n        firstMessage: `Hi! I'm the KenDev.Co scheduling assistant. How can I help you today?`,\n        model: {\n          provider: 'openai',\n          model: 'gpt-4',\n          systemMessage: this.buildSystemPrompt(context)\n        },\n        functions: [\n          this.getAvailabilityFunction(),\n          this.scheduleAppointmentFunction(),\n          this.sendSummaryToSpaceFunction()\n        ]\n      }\n    })\n  }\n\n  buildSystemPrompt(context) {\n    return `You are a professional scheduling assistant for ${context.companyName}.\n    Available team members: ${context.teamMembers.map(m => m.name).join(', ')}\n    Current date: ${new Date().toISOString()}\n    Meeting types: ${context.meetingTypes.join(', ')}\n    \n    Your role:\n    1. Understand the caller's needs\n    2. Check real-time availability\n    3. Schedule appropriate meetings\n    4. Send summaries to the team's Spaces channel\n    5. Handle rescheduling and cancellations professionally`\n  }\n}",
              language: 'typescript',
            },
            format: '',
            version: 2,
          },
          {
            type: 'heading',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Intelligent Follow-Up Automation',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            tag: 'h2',
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'The VAPI bot doesn\'t stop at scheduling. It maintains ongoing relationships with prospects and clients through intelligent follow-up calls that feel natural and personalized, while keeping your team informed through Spaces channels.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'list',
            children: [
              {
                type: 'listitem',
                children: [
                  {
                    type: 'text',
                    detail: 0,
                    format: 0,
                    mode: 'normal',
                    style: '',
                    text: '📞 Proactive outbound calls based on pipeline triggers',
                    version: 1,
                  },
                ],
                direction: 'ltr',
                format: '',
                indent: 0,
                version: 1,
                value: 1,
              },
              {
                type: 'listitem',
                children: [
                  {
                    type: 'text',
                    detail: 0,
                    format: 0,
                    mode: 'normal',
                    style: '',
                    text: '🎯 Personalized conversation based on previous interactions',
                    version: 1,
                  },
                ],
                direction: 'ltr',
                format: '',
                indent: 0,
                version: 1,
                value: 2,
              },
              {
                type: 'listitem',
                children: [
                  {
                    type: 'text',
                    detail: 0,
                    format: 0,
                    mode: 'normal',
                    style: '',
                    text: '📊 Real-time updates to CRM and team collaboration channels',
                    version: 1,
                  },
                ],
                direction: 'ltr',
                format: '',
                indent: 0,
                version: 1,
                value: 3,
              },
              {
                type: 'listitem',
                children: [
                  {
                    type: 'text',
                    detail: 0,
                    format: 0,
                    mode: 'normal',
                    style: '',
                    text: '🤖 AI-powered sentiment analysis and next-action recommendations',
                    version: 1,
                  },
                ],
                direction: 'ltr',
                format: '',
                indent: 0,
                version: 1,
                value: 4,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            listType: 'bullet',
            start: 1,
            tag: 'ul',
            version: 1,
          },
          {
            type: 'block',
            fields: {
              blockName: '',
              blockType: 'mediaBlock',
              media: blockImage.id,
            },
            format: '',
            version: 2,
          },
          {
            type: 'heading',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Spaces Integration: Conversations Meet Collaboration',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            tag: 'h2',
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Every VAPI conversation automatically flows into your Spaces channels, creating a seamless bridge between voice interactions and team collaboration. The AI provides conversation summaries, action items, and strategic recommendations directly in your chat.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'heading',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Advanced Voice Analytics & CRM Integration',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            tag: 'h3',
            version: 1,
          },
          {
            type: 'block',
            fields: {
              blockName: 'Voice Analytics',
              blockType: 'code',
              code: "// Voice Analytics & CRM Pipeline\nclass VoiceAnalytics {\n  async processCallCompletion(callData) {\n    const transcript = callData.transcript\n    const sentiment = await this.analyzeSentiment(transcript)\n    const keyTopics = await this.extractKeyTopics(transcript)\n    const actionItems = await this.generateActionItems(transcript)\n    \n    // Business AI Agent Analysis\n    const businessInsights = await this.BusinessAgent.analyzeConversation({\n      transcript,\n      sentiment,\n      contactInfo: callData.contact,\n      callOutcome: callData.outcome\n    })\n    \n    // Update CRM and notify team\n    await Promise.all([\n      this.updateCRMRecord(callData.contact.id, {\n        lastCallDate: new Date(),\n        sentiment: sentiment.overall,\n        nextActions: actionItems,\n        dealStage: this.predictDealStage(sentiment, keyTopics)\n      }),\n      \n      this.postToSpacesChannel(callData.spaceId, {\n        type: 'voice_call_summary',\n        caller: callData.contact.name,\n        duration: callData.duration,\n        sentiment: sentiment.overall,\n        keyTopics: keyTopics,\n        actionItems: actionItems,\n        businessInsights: businessInsights,\n        recordingUrl: callData.recordingUrl\n      })\n    ])\n  }\n}",
              language: 'typescript',
            },
            format: '',
            version: 2,
          },
          {
            type: 'heading',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Website Lead Capture & Voice Follow-Up',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            tag: 'h2',
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'When prospects fill out forms on your website or interact with your commerce platform, the VAPI bot can automatically initiate voice follow-ups within minutes, dramatically increasing conversion rates while your leads are still hot.',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            textFormat: 0,
            version: 1,
          },
          {
            type: 'block',
            fields: {
              blockName: 'Complete Sales Automation',
              blockType: 'banner',
              content: {
                root: {
                  type: 'root',
                  children: [
                    {
                      type: 'paragraph',
                      children: [
                        {
                          type: 'text',
                          detail: 0,
                          format: 0,
                          mode: 'normal',
                          style: '',
                          text: 'VAPI + Spaces creates a complete sales automation ecosystem: intelligent voice interactions, real-time team collaboration, AI-powered insights, and seamless CRM integration - all working together to maximize your revenue potential.',
                          version: 1,
                        },
                      ],
                      direction: 'ltr',
                      format: '',
                      indent: 0,
                      textFormat: 0,
                      version: 1,
                    },
                  ],
                  direction: 'ltr',
                  format: '',
                  indent: 0,
                  version: 1,
                },
              },
              style: 'success',
            },
            format: '',
            version: 2,
          },
        ],
        direction: 'ltr',
        format: '',
        indent: 0,
        version: 1,
      },
    },
    heroImage: heroImage.id,
    meta: {
      description:
        'Discover how VAPI.AI integration with Spaces enables intelligent voice scheduling, automated follow-ups, and seamless team collaboration for maximum sales efficiency.',
      image: heroImage.id,
      title: 'VAPI Scheduling: AI Voice Assistant Revolution',
    },
    relatedPosts: [], // this is populated by the seed script
    title: 'VAPI Scheduling: AI Voice Assistant Revolution',
  }
}
